bluecherrydvr/unity

ios/Runner/AppDelegate.swift, ios/Runner/Info.plist
I'll add Firebase configuration in a new pull.
=> feat: iOS platform-specific configuration

README.md
=> feat: project documentation

lib/api/api.dart, lib/api/api_helpers.dart, lib/firebase_messaging_background_handler.dart, lib/utils/methods.dart, lib/widgets/device_grid.dart, pubspec.lock
=> fix: missing camera screenshot thumbnail in notifications & final tweaks

ios/Podfile.lock, lib/firebase_messaging_background_handler.dart, lib/l10n/app_en.arb, lib/providers/settings_provider.dart, lib/utils/constants.dart, lib/utils/theme.dart, lib/widgets/device_tile.dart, lib/widgets/direct_camera.dart, lib/widgets/events_screen.dart, lib/widgets/settings.dart, pubspec.lock, pubspec.yaml
- Tweak tooltip styling.
- Re-design `EventPlayerScreen`.
- Upgrade build number.
- Customizable camera view fit options e.g. cover, fill & contain.
=> feat: final tweaks to iOS & android impl

lib/main.dart, lib/widgets/device_grid/desktop_device_grid.dart
Addresses https://github.com/bluecherrydvr/unity/discussions/42
=> Skip bad certificate error

lib/api/api.dart, lib/l10n/app_en.arb, lib/main.dart, lib/models/layout.dart, lib/providers/desktop_view_provider.dart, lib/providers/server_provider.dart, lib/widgets/add_server_wizard.dart, lib/widgets/device_grid/desktop/desktop_device_grid.dart, lib/widgets/device_grid/desktop/layout_manager.dart, lib/widgets/full_screen_viewer/full_screen_viewer.dart, lib/widgets/full_screen_viewer/mobile_viewer.dart, lib/widgets/hover_button.dart, lib/widgets/reorderable_static_grid.dart, packages/unity_video_player/unity_video_player/pubspec.yaml, packages/unity_video_player/unity_video_player_media_kit/lib/unity_video_player_media_kit.dart, packages/unity_video_player/unity_video_player_media_kit/pubspec.yaml, pubspec.lock, pubspec.yaml
fix: the layout is no longer duplicated when it's is edited
performance: the servers are no longer encoded/decoded from json when parsing from local cache
performance: upgraded `media_kit`; do not `await` on player dispose (Fixes #104)
fix: items on the device grid will no longer overflow out of the bottom of the screen
=> Stability checkup

lib/providers/desktop_view_provider.dart, lib/widgets/device_grid/desktop/layout_manager.dart
Fixes #108
For selected layout, it can be dragged around. For unselected layouts, drag the icon on the left.
https://github.com/bluecherrydvr/unity/assets/45696119/fb7745c8-49d1-41ab-8f5d-fa3186aa2840
=> Reorder layouts

lib/widgets/hover_button.dart, lib/widgets/ptz.dart, pubspec.lock
When PTZ is disabled, PTZ gestures no longer conflict with each other
=> Fix drag-and-drop

lib/widgets/desktop_buttons.dart
=> Fix window closing

.github/workflows/flutter_analysis.yml, .github/workflows/main.yml, bluecherry_appcast.xml, installer/windows-installer.iss, linux/debian/DEBIAN/control, linux/debian/usr/share/metainfo/bluecherry.appdata.xml, pubspec.yaml, snap/snapcraft.yaml
With this, every release published from now on will have its own files, allowing the user to download executables from old releases
=> Release files for each release

.github/workflows/main.yml
=> run main.yml on release:

lib/models/device.dart, lib/widgets/device_grid/desktop/desktop_sidebar.dart, lib/widgets/device_grid/video_status_label.dart
Previously, if the user had any special characters in their password, the streaming would fail to connect, although events would work properly. Now, both streaming and events work for this case.
The encoded URL is passed to MPV, which can now play the video correctly.
=> Correctly encode `userInfo` components before using them

lib/firebase_messaging_background_handler.dart, lib/main.dart, lib/models/device.dart, lib/providers/desktop_view_provider.dart, lib/providers/downloads_provider.dart, lib/providers/events_playback_provider.dart, lib/providers/mobile_view_provider.dart, lib/providers/server_provider.dart, lib/providers/settings_provider.dart, lib/providers/update_provider.dart, lib/utils/logging.dart, lib/utils/video_player.dart, lib/widgets/device_grid/desktop/desktop_device_grid.dart, lib/widgets/device_grid/desktop/desktop_sidebar.dart, lib/widgets/device_grid/desktop/stream_data.dart, lib/widgets/direct_camera.dart, lib/widgets/events/event_player_desktop.dart, lib/widgets/events/event_player_mobile.dart, lib/widgets/multi_window/window.dart, lib/widgets/player/live_player.dart, linux/CMakeLists.txt, packages/unity_multi_window/example/pubspec.lock, packages/unity_video_player/unity_video_player_main/lib/unity_video_player_main.dart, pubspec.lock, pubspec.yaml
Fix memory leak issues and ensures app functionalities are working properly
=> Linux stability

.github/workflows/build.yml, lib/main.dart, lib/models/layout.dart, lib/providers/home_provider.dart, lib/providers/settings_provider.dart, lib/providers/update_provider.dart, lib/utils/methods.dart, lib/utils/storage.dart, lib/utils/window.dart, lib/widgets/desktop_buttons.dart, lib/widgets/settings/desktop/updates.dart, lib/widgets/settings/mobile/settings.dart, lib/widgets/settings/shared/update.dart, packages/unity_video_player/unity_video_player_flutter/lib/unity_video_player_flutter.dart, packages/unity_video_player/unity_video_player_flutter/pubspec.yaml, pubspec.lock
=> feat: Embedded platforms support

lib/providers/settings_provider.dart, lib/screens/events_timeline/desktop/timeline.dart, lib/screens/players/event_player_desktop.dart, lib/screens/settings/events_and_downloads.dart
=> feat: Increase playback speed limit to 6.0

lib/main.dart, lib/providers/settings_provider.dart, lib/screens/downloads/downloads_manager.dart, lib/screens/events_browser/events_screen_mobile.dart, lib/screens/events_browser/filter.dart, lib/screens/events_timeline/events_playback.dart, lib/screens/home.dart, lib/screens/layouts/desktop/multicast_view.dart, lib/screens/layouts/desktop/sidebar.dart, lib/screens/layouts/video_status_label.dart, lib/screens/multi_window/single_camera_window.dart, lib/screens/multi_window/window.dart, lib/utils/window.dart, windows/runner/win32_window.cpp
=> Secondary window

lib/main.dart, lib/providers/desktop_view_provider.dart, lib/screens/multi_window/window.dart, lib/utils/app_links/app_links.dart, lib/utils/window.dart, lib/widgets/desktop_buttons.dart, packages/unity_multi_window/lib/unity_multi_window.dart, pubspec.lock, pubspec.yaml
=> Command Line Arguments

lib/providers/server_provider.dart
=> fix: Dump servers provider instance if not initialized yet

lib/main.dart, lib/providers/home_provider.dart, lib/providers/layouts_provider.dart, lib/providers/settings_provider.dart, lib/screens/events_timeline/desktop/timeline.dart, lib/screens/events_timeline/events_playback.dart, lib/screens/home.dart, lib/screens/layouts/desktop/layout_manager.dart, lib/screens/layouts/desktop/layout_view.dart, lib/screens/layouts/device_grid.dart, lib/screens/settings/application.dart, lib/screens/settings/settings_desktop.dart, lib/utils/keyboard.dart, lib/widgets/collapsable_sidebar.dart, lib/widgets/desktop_buttons.dart
=> Improve Keyboard Shortcuts

lib/api/events.dart, lib/models/event.dart, lib/providers/events_provider.dart, lib/screens/events_timeline/events_playback.dart
Events were being removed if the system recognized them as not the same day because timezone offset was not being considered.
=> hotfix: Timeline of Events fetching

ios/Podfile, ios/Runner/Info.plist, lib/utils/app_links/app_links.dart
* Add missing permissions on iOS
* Add `--mdk` flag, that uses MDK to render videos instead of MPV
=> General fixes

lib/api/api.dart, lib/l10n/app_en.arb, lib/l10n/app_fr.arb, lib/l10n/app_pl.arb, lib/l10n/app_pt.arb, lib/l10n/generated/app_localizations.dart, lib/l10n/generated/app_localizations_en.dart, lib/l10n/generated/app_localizations_fr.dart, lib/l10n/generated/app_localizations_pl.dart, lib/l10n/generated/app_localizations_pt.dart, lib/models/device.dart, lib/providers/events_provider.dart, lib/screens/events_browser/date_time_filter.dart, lib/screens/events_browser/sidebar.dart, lib/screens/events_timeline/desktop/timeline_sidebar.dart, lib/screens/layouts/desktop/device_info_dialog.dart
Addresses #258
Server PR https://github.com/bluecherrydvr/bluecherry-apps/pull/740
=> Oldest recording

lib/api/api.dart, lib/api/events.dart, lib/models/event.dart, lib/models/server.dart, lib/providers/downloads_provider.dart, lib/screens/players/event_player_desktop.dart, lib/screens/players/event_player_mobile.dart, lib/utils/video_player.dart, lib/widgets/desktop_buttons.dart
Remove user:pass@host from Uri.https(...)
Replace media URL rewrites
Add Authorization header
--
Fixes #331
=> Web: Cleanup / authorization header added for events
